if (MSVC)
	if (MSVC_TOOLSET_VERSION EQUAL 143)
		set(PLATFORM_NAME "2022")
	elseif (MSVC_TOOLSET_VERSION EQUAL 142)
		set(PLATFORM_NAME "2019")
	elseif (MSVC_TOOLSET_VERSION EQUAL 141)
		set(PLATFORM_NAME "2017")
	elseif (MSVC_TOOLSET_VERSION EQUAL 140)
		set(PLATFORM_NAME "2015")
	endif()
endif()

function(set_target_name_exe TARGET NAME)
	set_target_properties(${TARGET} PROPERTIES
		OUTPUT_NAME "${NAME}"

		DEBUG_POSTFIX "_debug"
		RELEASE_POSTFIX "_release"
	)
endfunction()

function(set_engine_out_dir TARGET PATH)
	if (CMAKE_SIZEOF_VOID_P EQUAL 4 AND WIN32)
		set(PLATFORM_STR "win32")
	elseif (WIN32)
		set(PLATFORM_STR "win64")
	endif()

	set_target_properties(${TARGET} PROPERTIES
		RUNTIME_OUTPUT_DIRECTORY_DEBUG 				${PATH}/${PLATFORM_STR}
		RUNTIME_OUTPUT_DIRECTORY_RELEASE 			${PATH}/${PLATFORM_STR}
		RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO		${PATH}/${PLATFORM_STR}
		RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL 		${PATH}/${PLATFORM_STR}
		RUNTIME_OUTPUT_DIRECTORY_FINAL 				${PATH}/${PLATFORM_STR}
	)
endfunction()

function(set_target_out_dir TARGET PATH)
set_target_properties(${TARGET} PROPERTIES
	RUNTIME_OUTPUT_DIRECTORY_DEBUG ${PATH}
	RUNTIME_OUTPUT_DIRECTORY_RELEASE ${PATH}
	RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO ${PATH}
	RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL ${PATH}
	RUNTIME_OUTPUT_DIRECTORY_FINAL ${PATH}
)
endfunction()
